version: "3.3"
services:
  php:
    container_name: php
    build: php
    ports:
      - "80:80"
      - "5173:5173"
      - "9000:9000"
    volumes:
      - ./src:/usr/local/apache2/htdocs/
    working_dir: /usr/local/apache2/htdocs/cupra-tribe
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
        - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongodb/db:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: [--auth]
  mongo-express:
    image: mongo-express:latest
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASS}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASS}@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_PASS}
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
